logger:
  level: "debug"

server:
  port: 8080

mongo:
  host: ""
  port: 27017
  replica-set: rs0
  database: "auth"
  migrations:
    enabled: true
    auto-migrate: true

observability:
  tracing-enabled: true
  otel-collector-endpoint: ""

# Initial super admin user (created on first startup if not exists)
# Password should be set via ADMIN_INITIAL_USER_PASSWORD environment variable
admin:
  initial-user:
    enabled: true
    first-name: "Super"
    last-name: "Admin"
